// generated by unplugin-vue-components
// We suggest you to commit this file into source control
// Read more: https://github.com/vuejs/vue-next/pull/3399

declare module 'vue' {
  export interface GlobalComponents {
    BooleanDisplay: typeof import('./.vitepress/theme/components/BooleanDisplay.vue')['default']
    DemoBlock: typeof import('./.vitepress/theme/components/DemoBlock.vue')['default']
    DemoContainer: typeof import('./.vitepress/theme/components/DemoContainer.vue')['default']
    ElTableNext: typeof import('el-table-next')['ElTableNext']
    Home: typeof import('./.vitepress/theme/components/Home.vue')['default']
    HomeFeatures: typeof import('./.vitepress/theme/components/HomeFeatures.vue')['default']
    HomeFooter: typeof import('./.vitepress/theme/components/HomeFooter.vue')['default']
    HomeHero: typeof import('./.vitepress/theme/components/HomeHero.vue')['default']
  }
}

export { }
